### PR TITLE
V3.5 compatibility updates

### PR DESCRIPTION
**Pull request by jyucis**
HOVERZOOM-1

### CODE REVIEW

**Review by bencrouse — CHANGES_REQUESTED** [review]
So now we gotta upgrade jQuery zoom? :(

**Comment by jyucis** [comment]
This is going to require updating the two workarea plugins that workarea-hover-zoom depends on.

**Review by bencrouse — CHANGES_REQUESTED** [review]
I guess we're still waiting on the hover zoom?

**Comment by bencrouse** [comment]
@jyucis what are we doing here?

**Review by bencrouse — CHANGES_REQUESTED** [review]
Looks like a relevant build failure there...

**Review by bencrouse — APPROVED** [review]

**Pull request merged**
